name: crud_module
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^3.0.7
  http: ^0.13.6

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
